### ISSUE TITLE
v1.3 Updates

### ISSUE THREAD

**Issue by B-Reif** [alpine-alpaca/asefile#1]
Aseprite v1.3 will bring some [changes to the Aseprite file specification](https://gist.github.com/dacap/35f3b54fbcd021d099e0166a4f295bab). This includes a few new types of data:

- Cel types
- User data chunks, one per tag
- Tileset chunks

**Comment by alpine-alpaca** [comment]
Thanks for the link to the spec. I'll take a look.

**Comment by B-Reif** [comment]
I opened a draft PR in #2 to start working on some of the changes. I'll keep pushing commits there.
