### ISSUE TITLE
"Indexed colors without a palette" for indexed image that has a palette

### ISSUE THREAD

**Issue by cosmicchipsocket** [alpine-alpaca/asefile#12]
Asefile does not seem to think that this indexed color image has a palette, even though it has a full 256-color palette stored in it. Here's what it looks like in Aseprite:

![2022-01-15 13_26_21-animation_tracks ase - Aseprite v1 2 28-x64](https://user-images.githubusercontent.com/34800072/149633458-51e53aa9-8691-4fcb-84b5-d031fa83c016.png)

For some reason this gives `Invalid Aseprite input: Indexed colors without a palette`

The source .ase file (had to zip this or Github wouldn't let me attach it):
[animation_tracks.ase.zip](https://github.com/alpine-alpaca/asefile/files/7875591/animation_tracks.ase.zip)

**Comment by cosmicchipsocket** [comment]
It appears that Aseprite is only saving the old style palette chunk (0x0004) if there are exactly 256 colors in the palette. According to the documentation on the file format:

"Ignore this chunk if you find the new palette chunk (0x2019)"

We aren't finding the new palette chunk in this file, so we should be using the old palette chunk to populate the palette data.

**Comment by cosmicchipsocket** [comment]
Wrote a fix for this in #13

**Comment by alpine-alpaca** [comment]
I merged Pr #13 and released it with v0.3.4.
