### ISSUE TITLE
TilesetsById iterator

### ISSUE THREAD

**Issue by B-Reif** [alpine-alpaca/asefile#14]
The `map` function for `TilesetsById` has been commented out. Without it, it's impossible to iterate over entries within the inner `HashMap`. It would be nice to either reinstate the method (rust naming conventions suggest this method be called `.inner()`), or implement other access methods like a custom iterator.

**Comment by B-Reif** [comment]
Because `TilesetId` is now a private type, we can't actually expose the inner value. #15 adds an `iter` function to iterate over the tileset values.

**Comment by alpine-alpaca** [comment]
Merged and released with v0.3.3
